name: Gerar APK Namaguederaz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Instalar dependências
        run: npm install

      - name: Criar projeto Android
        run: npx cap add android

      - name: Sincronizar Capacitor
        run: npx cap sync android

      - name: Configurar Android SDK
        uses: android-actions/setup-android@v4
        with:
          packages: ''

      - name: Instalar SDK Android
        run: |
          yes | sdkmanager --licenses >/dev/null || true
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Gerar APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Namaguederaz-APK
