name: Gerar APK Namaguederaz

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar arquivos do repositorio
        uses: actions/checkout@v4

      - name: Preparar projeto
        run: |
          unzip -q Namaguederaz_CORRIGIDO.zip -d projeto
          cd projeto/Namaguederaz_FINAL
          npm install
          npx cap add android
          npx cap sync android

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Configurar Android
        uses: android-actions/setup-android@v3

      - name: Instalar Android SDK
        run: |
          sdkmanager "platform-tools" "platforms;android-35" "build-tools;35.0.0"

      - name: Gerar APK
        run: |
          cd projeto/Namaguederaz_FINAL/android
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: Namaguederaz-APK
          path: projeto/Namaguederaz_FINAL/android/app/build/outputs/apk/debug/app-debug.apk
